pmem/vmemcache

- .gitignore
Hide some generic junk.  This does not include actually built binaries, tests' private dirs, etc — would be nice to add them later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/12)
> git ignores

- tests/CMakeLists.txt
- tests/test-mt.cmake
- tests/vmemcache_test_mt.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/23)
> Add multi-threaded test

- src/vmemcache.c
- src/vmemcache_repl.c
- src/vmemcache_repl.h
The pointer to an element of the replacement policy list's
can be accessed (read and written) only under the lock
inside the replacement policy module in order to avoid
race conditions. This is a continuation of the incomplete
fix e89a003f.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/27)
> repl: make _use and _evict take a reference to the pointer

- utils/check_license/check-license.c
This fixes a couple of warnings when compiling check-license with a new enough gcc.
Don't even try reading the code — it'll make you weep and lose the last shreds of faith in humanity.  It mixes C strings with null-padded-not-terminated buffers, which almost always _are_ filled to the brim, thus not exploding only because the random memory past the end tends to be 0 — and that's just some of the badness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/26)
> silence warnings in check-license

- src/valgrind_internal.h
- src/vmemcache.c
... to make it understand the thread-safe reference counting
according to [7.5. Hints and Tips for Effective Use of Helgrind]
at:
http://cs.swan.ac.uk/~csoliver/ok-sat-library/internet_html/\
doc/doc/Valgrind/3.8.1/html/hg-manual.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/28)
> add annotations for Valgrind

- utils/docker/images/Dockerfile.fedora-28
... because we need also the Valgrind's header files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/38)
> docker: add valgrind-devel package to the Fedora Docker image

- src/vmemcache_index.c
The current implementation can cause a warning (below),
so let's replace the struct with a char buffer to silent it.
```
warning: field 'entry' with variable
sized type 'struct cache_entry' not at the end
of a struct or class is a
GNU extension [-Wgnu-variable-sized-type-not-at-end]
struct cache_entry entry;
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/35)
> replace the struct with a char buffer to silent a warning

- src/critnib.c
I can't reproduce locally (without an older environment), but travis runs an older version of gcc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/33)
> fix a sign conversion warning

- src/file.c
In preparation for the kernel switching device-dax instances from the
"/sys/class/dax" subsystem to "/sys/bus/dax" [1], teach the device-dax
instance detection to be subsystem-type agnostic.
Note that the subsystem switch will require an administrator, or distro,
opt-in. The opt-in will either be at kernel compile time by disabling
the default compatibility driver in the kernel, or at runtime with a
modprobe policy to override which kernel module services device-dax
devices. The daxctl utility [2] will ship a command to install the
modprobe policy and include a man page that lists the potential
regression risk to older PMDK and other userspace tools that are hard
coded to "/sys/class/dax".
[1]: https://lwn.net/Articles/770128/
[2]: https://github.com/pmem/ndctl/tree/master/daxctl …
> Make detection of device-dax instances more robust

- src/vmemcache_heap.c
- src/vmemcache_repl.c
This PR reverts PRs: #18 and #22, because we are not sure if spin locks will be really faster and if they will be actually needed, but they cause problems when tests are run under Helgrind right now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/53)
> Replace spin lock with mutex in heap and replacement policy

- src/libvmemcache.h
- src/libvmemcache.map
Remove non-existing functions from libvmemcache.map and libvmemcache.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/52)
> Remove non-existing functions from libvmemcache.map and libvmemcache.h

- src/vmemcache.c
It's not the primary result of vmemcache_get(), thus it's reasonable for the user to omit it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/80)
> accept missing *vsize

- src/util.c
- src/util.h
- src/vmemcache.h
- src/vmemcache_index.c
- src/vmemcache_index.h
Should work around lock contention on a single mutex.
There's a cost to pay, though: hashing the key may take significant time.  This commit uses FNV-1a hash, but that's easy to replace.
Edit: sharding is now switchable at runtime — set ``VMEMCACHE_NO_SHARDING`` to disable.  To be replaced once/if we have proper runtime configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/45)
> Index sharding

- src/vmemcache.c
- src/vmemcache.h
- src/vmemcache_index.c
- src/vmemcache_repl.c
- src/vmemcache_repl.h
Replace `struct repl_p repl` with `struct repl_p *repl`
in the `struct vmemcache` in preparation to add a 'free' callback
to vmcache_index_delete() and critnib_delete().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/76)
> clean up types and includes of headers

- benchmarks/bench_micro.c
- src/critnib.c
- src/critnib.h
- src/vmemcache.c
- src/vmemcache.h
- src/vmemcache_index.c
- src/vmemcache_index.h
- tests/vmemcache_test_mt.c
vmemcache_delete() does not free all allocated cache entries yet. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/85)
> Fix memory leaks in vmemcache_delete

- benchmarks/bench_simul.c
Generally pointless for multi-threaded runs, but n_threads=1 is a valid scenario.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/94)
> simul: actually use the seed parameter

- benchmarks/bench_simul.c
Most of the sizes used come in large units, so let's make them human-readable.
We also use -1ULL as "unlimited", "18446744073709551615" isn't exactly recognizable as a special number at a glance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/96)
> simul: some pretty-printing of parameter values

- src/util.h
Replace wrong 'memory_order_seqcst'
with correct 'memory_order_seq_cst'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/101)
> util: fix util_atomic_load/store_explicit32/64

- benchmarks/bench_simul.c
A knob to make the distribution either strongly skewed towards a small number of keys, or to access a key only once or nearly so.  Obviously, both extremes are degenerate enough to not make good use of the cache, but the fun is in the middle...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/105)
> simul: key_diversity

- benchmarks/bench_simul.c
It doesn't provide any meaningful benchmarking — but gives us something to test eviction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/104)
> junk_start to start with a full cache

- src/libvmemcache.h
- src/libvmemcache.map
- src/vmemcache.c
- src/vmemcache.h
Turns out our benchmarks are not very realistic — the cache looks completely different after minutes of work than from an empty start, and what we're interested in is how it'd be after a month of use.  Thus, an env var or similar is no good — the benchmark will need to simulate ʟᴏᴛꜱ of operations, and only then enable back full functionality that's supposed to be measured.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/107)
> API: add vmemcache_config_set()

- benchmarks/bench_simul.c
- src/vmemcache.c
A benchmark with fancy keys but no actual values is not realistic at all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/106)
> simul: insert values bigger than 1 byte

- benchmarks/bench_simul.c
If ``latency_samples`` is given, that many n-tiles will be dumped, for cache hits and misses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/109)
> simul: latency stats as CSV

- benchmarks/bench_simul.c
- src/vmemcache.c
Can be:
* index: nothing but gets and puts into index (evicts won't trigger)
* alloc: index and allocator: we get cache fragmentation, etc
* full: probably dominated by memcpy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/112)
> simul: different benchmark types to select layers to disable

- tests/vmemcache_test_basic.c
- vmemcache_new with NULL path
- vmemcache_new with nonexistent path
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/116)
> test: add more basic tests

- benchmarks/bench_simul.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/126)
> bench: use vmemcache_errormsg() instead of strerror()

- CMakeLists.txt
- benchmarks/CMakeLists.txt
- benchmarks/rand.c
Would fail on Ubuntu 16.04, Debian Stretch, openSuSE 14, any CentOS.
The fallback is very weak but we don't need good randomness for seeding benchmarks.  Beware when taking this code for other projects, though!  Or just wait till old musty distro releases get EOLed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/119)
> Fix compilation with glibc headers older than 2.25.

- src/vmemcache.c
- tests/vmemcache_test_basic.c
That's not the intended way to use the API, but there are uses for not caring about the contents yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/120)
> Fix a crash with _get(vbuf=null).

- src/vmemcache.c
Do not error out if the element with the given key
is being evicted just now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/127)
> evict: do not error out if the element is being evicted just now

- benchmarks/bench_simul.c
- tests/test-bench-simul.cmake
Let it get filled up and fragmented.  Good warm up takes a good deal longer than 100k ops, but I'm starting with a conservative default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/133)
> simul: warm_up of the cache

- benchmarks/bench_simul.c
Make the lengths of values independent between runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/134)
> simul: salt the key:vsize hash

- doc/vmemcache.md
- src/libvmemcache.h
- src/vmemcache.c
- tests/test_helpers.h
- tests/vmemcache_test_basic.c
- tests/vmemcache_test_mt.c
There are rare cases when the value the user provided wasn't delivered.  Let's not have nasty surprises — this kind of failures is very difficult to test against, and workarounds disrupt the workflow.
As a bonus, this simplifies the on_miss code path and makes it faster.
It affects the stats (wrt #124) — I fixed the non-controversial case of no on_miss; we still need to agree what to return when the callback exists and fails or succeeds.
Fixes #122.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/137)
> Guarantee that an on_miss callback fulfills a failed get request.

- src/vmemcache.c
- src/vmemcache.h
- src/vmemcache_heap.c
- src/vmemcache_heap.h
This patch speeds-up bench_simul with default parameters by ~4x by aggregating fragment allocations/deallocations under a single lock acquire/release pair.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/140)
> heap: aggregate fragment alloc/free for single entry

- benchmarks/bench_simul.c
- doc/vmemcache.md
- src/vmemcache.c
- tests/vmemcache_test_basic.c
The return value of 0 was too overloaded: it meant reading past vsize, vsize=0 — and non-existing key.  So let's make the latter return -1 (an error) with errno of ENOENT.
[This includes #137 — thus marked as draft despite being ready, as Reviewable doesn't handle incremental PRs well.]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/138)
> API: make failed get return -1, ENOENT

- benchmarks/bench_simul.c
We want to tell apart warm_up from the rest, without deoptimizing everything else.
It'd be best to disable perf while in warm_up completely, but unless you know how, this kind of works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/142)
> Let warm_up show up on perf.

- tests/CMakeLists.txt
Using the same "private" directory for different versions of the same test, and tearing them up after each run, doesn't work concurrently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/145)
> Unbreak ｢ctest -j｣.

- tests/vmemcache_test_utilization.c
Currently we read an arbitrarily long value
from a single-byte variable on the stack,
what can easily cause a segmentation fault error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/151)
> test: allocate a value buffer in the utilization test

- benchmarks/bench_simul.c
The warning is a false positive due to gcc's flow analyzer behaving weirdly.
Interestingly, it's not because it doesn't **see** the variable having no way of being changed from the outside — as moving the check **later** avoids the warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/152)
> Fix an (invalid) compiler warning.

- benchmarks/bench_simul.c
- src/libvmemcache.h
- src/os_thread_posix.c
- src/vmemcache.c
After even modest warm up, the allocator rapidly degenerates.  Thus, let's make it easier to run long warm ups quickly.
So let's skip memcpy during it — instead, clobber the cache just enough to prefault it.
Also, long warm_up may get a thread faster than others, resulting in stragglers to have a nice uncontended cache, falsifying the results.  Thus, let's synchronize all threads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/146)
> simul: warm_up improvements

- tests/example.c
If 'minimum pool size' or 'minimum size of extent' changes,
vmemcache_new() can fail and the test would segfault,
so:
1) the predefined constants:
- VMEMCACHE_MIN_POOL and VMEMCACHE_MIN_EXTENT
have to be used instead of hardcoded values and
2) failure of vmemcache_new() has to be handled properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/156)
> test: fix example test

- src/vec.h
This significantly reduces DRAM footprint of vmemcache because
right now all VEC(struct heap_extent) structures are initialized
with 1 kilobyte of entries which are most likely never used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/159)
> vec: reduce initial size of vec to 1

- benchmarks/bench_simul.c
It may be interesting whether we're doing junk_start, warm_up or the real run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/158)
> simul: print what stage the benchmark is doing

- doc/vmemcache.md
pandoc requires a pretty quirky syntax; naïve markdown results in reversed indentation — option header was to the right, body text to the left.  This reformatting produces a more man-like page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/168)
> man: produce proper definition lists

- benchmarks/bench_simul.c
- src/critnib.c
- src/vmemcache.c
- tests/test_helpers.h
- tests/vmemcache_test_utilization.c
It's better to use appropriate types, such as *intptr_t* for pointer, even when their width is known — more readable, and will make eventual porting to platforms with a weird type scheme such as Windows easier.
There's also a 32-bit crash fix due to printf mismatch.  I did not bother to fix warnings, merely made vmemcache build and pass all tests — we don't care about 32-bit, but if I can make it all green at such a small cost, why not?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/172)
> int size fixes

- CMakeLists.txt
Just a WARNING rather than FATAL_ERROR.  Do we want the latter?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/180)
> Make cmake complain if pandoc is not present.

- src/vmemcache.c
- src/vmemcache.h
A low-hanging fruit for reducing DRAM usage by 8 bytes per entry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/183)
> cut cache_entry refcounts to 32 bits

- src/vmemcache_heap.c
There's no need for costly sync_adds when already under a mutex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/195)
> speed up stats for heap

- tests/vmemcache_test_heap_usage.c
It fixes Klocwork issue #399.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/198)
> test: fix possible null-pointer dereference in test_heap_usage

- benchmarks/bench_micro.c
- benchmarks/bench_simul.c
- src/libvmemcache.h
- src/libvmemcache.map
- src/vmemcache.c
- src/vmemcache.h
- tests/example.c
- tests/vmemcache_test_basic.c
- tests/vmemcache_test_heap_usage.c
- tests/vmemcache_test_mt.c
- tests/vmemcache_test_utilization.c
Marcin's version, which I like the most.
There's no separate "config" object — the cache gets configured, then opens a file.  This way, some parameters might remain settable at later stages.  Also, it may be possible to open multiple backing files for a single cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/197)
> new creation API: separate _open() step

- src/critnib.h
- src/vmemcache.c
- src/vmemcache.h
- src/vmemcache_index.c
- src/vmemcache_index.h
It takes adding 256 values to query this stuff, without a need for extra locks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/207)
> keep data about index size in the shards

- src/critnib.h
- src/vmemcache.c
- src/vmemcache.h
- src/vmemcache_heap.h
- src/vmemcache_index.c
- src/vmemcache_index.h
Alas, get counts still require a sync, but at least it's sharded now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/208)
> Store operation counts per shard.

- doc/vmemcache.md
Just a stylistic wording change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/221)
> doc: don't repeat "lib"

- src/CMakeLists.txt
- src/fast-hash.c
- src/fast-hash.h
- src/vmemcache_index.c
- utils/check_license/file-exceptions.sh
In an index-only benchmark, improves time from 2.26 to 1.97.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/217)
> Use fast-hash for sharding.

- src/mmap.c
On btrfs, this disables its data crash safety features, improving performance and avoiding ENOSPC.  The CoW mode is enabled by default even on DAX — it copies every page once per commit (usually 30 seconds).  That's a huge waste of time for a volatile cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/230)
> Set inode attributes to enable nocow.

- src/util.h
The former is long obsolete, and toolchains have already started dropping it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/234)
> __sync_fetch → __atomic_fetch

- tests/twolevel.c
Instead of arguing that this variable can't overflow, let's make this obvious.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/239)
> Placate a static checker (Klocwork).

- benchmarks/benchmark_time.c
Causes a random test failure on slow machines.  Revealed by Reproducible Builds where eg. i386 [failed every time](https://tests.reproducible-builds.org/debian/history/vmemcache.html), but I didn't notice that until now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/243)
> fix a time_t wraparound on 32-bit
