pmem/vmemcache

.gitignore
README.md
tests/CMakeLists.txt
tests/test.h
utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/2)

various minor fixes

---

src/vmemcache_heap.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/5)

Implement simple vmemcache linear allocator

---

src/vmemcache_repl.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/6)

Implement replacement policies for vmemcache

---

src/CMakeLists.txt
src/vmemcache.c
src/vmemcache_index.c
src/vmemcache_index.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/11)

add abstraction layer for vmemcache indexing API

---

src/vmemcache.c
src/vmemcache.h
src/vmemcache_index.c
src/vmemcache_index.h
src/vmemcache_repl.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/14)

references have to be changed under locks

---

src/vmemcache_repl.c
src/vmemcache_repl.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/15)

repl_p_evict should zero pointer to the evicted element

---

src/vmemcache_repl.c

STAILQ_REMOVE is far too slow - it kills performance of _get().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/17)

replace STAILQ with TAILQ in replacement policy

---

src/vmemcache.c
src/vmemcache.h
src/vmemcache_index.c
src/vmemcache_repl.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/7)

Implement libvmemcache API

---

src/vmemcache_heap.c

Spin lock is much faster than mutex in case of the heap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/18)

heap: replace mutex with spin lock

---

src/sys/queue.h
src/vmemcache_repl.c
src/vmemcache_repl.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/20)

queue: add TAILQ_MOVE_TO_TAIL

---

src/vmemcache_repl.c

Spin lock is faster than mutex in case of the replacement policy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/22)

repl: replace mutex with spin lock

---

src/vmemcache.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/24)

evict(NULL) cannot give up if it finds a key being evicted just now

---

utils/docker/images/Dockerfile.fedora-28
utils/docker/images/Dockerfile.ubuntu-18.04

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/34)

docker: add Valgrind to Docker images

---

tests/CMakeLists.txt
tests/helpers.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/30)

test: set timeout and print outputs

---

tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/41)

test: free cache before each test

---

CMakeLists.txt
benchmarks/CMakeLists.txt
benchmarks/bench_micro.c
benchmarks/benchmark_time.c
benchmarks/benchmark_time.h
tests/CMakeLists.txt
tests/test-bench-mt.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/10)

add micro benchmark

---

tests/CMakeLists.txt
tests/helpers.cmake
tests/vmemcache_test_mt.c
utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/29)

test: add Helgrind and Memcheck multi-threaded test

---

tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/44)

test: add 2 new subtests to vmemcache_test_basic

---

utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/39)

docker: print info about the configuration being run

---

benchmarks/bench_micro.c

It is only a refactor of the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/43)

bench: prepare micro benchmark to add new tests

---

src/vmemcache.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/56)

replace __sync_fetch_and_* with util_fetch_and_*64

---

tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/57)

test: print out parameters of the MT-test

---

tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/40)

test: add get+put multi-threaded test

---

tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/55)

test: fix setting number of operations

---

README.md
codecov.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/59)

Travis & CodeCov badges & codecov configuration

---

benchmarks/bench_micro.c
tests/test_helpers.h
tests/vmemcache_test_basic.c
tests/vmemcache_test_mt.c

Rename tests/vmemcache_tests.h to src/vmemcache_common.h
and add str_to_unsigned() to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/63)

rename header file and add str_to_unsigned()

---

src/libvmemcache.h
src/libvmemcache.map
src/vmemcache.c
src/vmemcache.h
src/vmemcache_heap.c
src/vmemcache_heap.h
tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/49)

add statistics

---

benchmarks/bench_micro.c
tests/test_helpers.h
tests/vmemcache_test_basic.c
tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/46)

bench: add benchmark for vmemcache_get()

---

tests/test-mt.cmake
tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/54)

test: limit number of threads and ops in Helgrind test

---

tests/test_helpers.h

<stddef.h> is for `NULL` and <stdlib.h> is for `strtoul`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/67)

test: add missing includes of headers

---

src/file.c
src/file_posix.c
src/mmap.c
src/os_posix.c
src/os_thread_posix.c
src/util.c
src/util_posix.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/60)

Ifdef out dead code.

---

src/vmemcache.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/64)

fix setting cache size on DAX device

---

benchmarks/bench_micro.c
src/libvmemcache.h
src/vmemcache.c
src/vmemcache_index.c
src/vmemcache_index.h
tests/vmemcache_test_basic.c
tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/72)

make type of key and value void* instead of char*

---

tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/71)

test: add test for cache entries bigger than 1kB

---

src/libvmemcache.h
src/vmemcache.c
src/vmemcache.h
src/vmemcache_heap.c
tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/74)

add statistic 'current number of cache entries' and some comments

---

src/critnib.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/81)

free critnib nodes during teardown

---

tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/82)

test: fix one check in basic test

---

tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/86)

test: prepare the basic test to add new replacement policies

---

benchmarks/bench_micro.c
tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/90)

Do not call return/goto after FATAL

---

benchmarks/bench_micro.c
benchmarks/bench_simul.c
tests/test_helpers.h
tests/vmemcache_test_basic.c
tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/89)

Replace FATAL() with UT_FATAL() and ERROR() with UT_ERR()

---

tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/92)

 test: fix type of a key

---

tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/98)

test: abort if vmemcache_get() fails in worker_thread_get()

---

src/vmemcache_index.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/99)

Replace free() with Free() and malloc() with Malloc()

---

src/critnib.c

There's no need to for explicit leaves — the key is a part of the entry (value) struct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/97)

unleavened critnib

---

benchmarks/bench_simul.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/100)

bench: print statistics at the end

---

tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/111)

test: vmemcache_new tests for 0 and -1 sized pool

---

src/libvmemcache.h
src/vmemcache.c
tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/93)

Add MT test with vmemcache_put() called in the on-miss callback

---

benchmarks/bench_simul.c

Set "latency_file".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/113)

simul: dump latencies to a file rather than stdout

---

benchmarks/bench_simul.c
src/libvmemcache.h
src/vmemcache.c
src/vmemcache.h

No allocations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/114)

simul: index+repl benchmark

---

benchmarks/bench_simul.c

Note that, unlike puts, every thread needs its own piece of memory of given size.  Which, for 100 threads at get_size=4GB requires 400GB DRAM...
Fortunately, we're hardly ever going to use this param.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/117)

simul: exercise big gets

---

benchmarks/bench_simul.c
tests/test_helpers.h

No exp distribution yet — there's a certain quarrel about the implementation...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/115)

simul: obey min_size, allow choosing distribution

---

src/libvmemcache.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/130)

fix name of the argument of vmemcache_delete() in the main header file

---

doc/vmemcache.md

No proper build system, etc, yet.  Formatting needs improvements, too (what's our equivalent for .TP?).
@wlemkows: as our doc mistress, could you please review this and educate me wrt preferred build syste/templates/etc for new projects?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/121)

First stab at documentation.

---

benchmarks/bench_simul.c

Just a no-change move, will be used by commits with lengthier review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/132)

simul: make the benchmark loop a function

---

benchmarks/bench_simul.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/128)

bench: print stats in case of fatal error

---

tests/CMakeLists.txt
tests/test-utilization.cmake
tests/test_helpers.h
tests/vmemcache_test_utilization.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/47)

test: add fragmentation test

---

tests/vmemcache_test_utilization.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/135)

test: remove evicting the cache before vmemcache_delete()

---

src/vmemcache.c
tests/vmemcache_test_basic.c

That's the appropriate errno value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/123)

return ENOSPC on puts

---

src/critnib.h
src/vmemcache_index.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/141)

index: use pthread RW-lock instead of mutex

---

benchmarks/bench_simul.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/136)

bench: print hits and size of used pool in percents

---

doc/vmemcache.md
src/CMakeLists.txt
src/os_thread_posix.c
src/ringbuf.c
src/ringbuf.h
src/util.h
src/vmemcache.c
src/vmemcache_repl.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/139)

LRU with ring buffer

---

benchmarks/bench_micro.c
benchmarks/bench_simul.c
doc/vmemcache.md
src/libvmemcache.h
src/vmemcache.c
src/vmemcache.h
src/vmemcache_heap.c
src/vmemcache_heap.h
tests/vmemcache_test_basic.c
tests/vmemcache_test_mt.c
tests/vmemcache_test_utilization.c

Ref: #110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/148)

replace all 'segment's and 'fragment's with 'extent'

---

tests/CMakeLists.txt
tests/example.c
tests/test-example.cmake

Alas, the required license spam makes this example pretty unreadable, thus ill fit for human consumption.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/149)

An example that doubles as an out-of-tree test.

---

tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/155)

test: evict nonexistent key

---

tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/144)

tests: add getting big key case

---

src/CMakeLists.txt

I'd like to be able to `#include <libvmemcache.h>` like the docs say...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/147)

｢make install｣

---

src/vec.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/160)

vec: fix copyright date

---

benchmarks/bench_simul.c
doc/vmemcache.md
src/libvmemcache.h
src/vec.h
src/vmemcache.c
src/vmemcache_heap.c
src/vmemcache_heap.h
tests/vmemcache_test_basic.c
tests/vmemcache_test_utilization.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/153)

heap: merge freed extents

---

tests/test_helpers.h
tests/vmemcache_test_basic.c
tests/vmemcache_test_utilization.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/154)

test: put in on_evict cb

---

doc/CMakeLists.txt

Need to tell cmake what to say and what to delete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/170)

doc: show what's being done, fix "make clean"

---

tests/test_helpers.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/171)

avoid a "function not used" warning

---

tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/175)

test: stat with wrong size

---

README.md

No valgrind means limited tests, no pandoc means no man page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/178)

mention optional b-deps in README

---

utils/docker/images/Dockerfile.ubuntu-18.04

The man page wants it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/179)

B-Dep on pandoc on docker/ubuntu.

---

CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/177)

install man page

---

CMakeLists.txt

Add '-Werror=incompatible-pointer-types' always
and '-Werror' in developer mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/185)

add compiler flags

---

tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/186)

test: fix using given seed

---

CMakeLists.txt
README.md
benchmarks/bench_simul.c
doc/vmemcache.md
src/CMakeLists.txt
src/vmemcache.c
src/vmemcache_heap.c
src/vmemcache_heap.h
tests/vmemcache_test_basic.c
tests/vmemcache_test_mt.c
tests/vmemcache_test_utilization.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/163)

make it possible to ifdef out statistics

---

tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/187)

test: add test for data integrity

---

tests/CMakeLists.txt
tests/test-heap-usage.cmake
tests/vmemcache_test_heap_usage.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/169)

test: heap usage test

---

src/vmemcache_repl.c
tests/test-mt.cmake
tests/vmemcache_test_mt.c

repl_p_lru_evict can hardly fail, so try everything before failing
Fixes: #164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/165)

repl_p_lru_evict: try everything before failing

---

CMakeLists.txt
README.md
packages.cmake
utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/181)

make packages

---

benchmarks/tools/benchconfig.py.example

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/176)

simul: fix benchconfig.py.example

---

tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/194)

test: use atomic load and atomic store to read/write keep_running

---

src/vmemcache.c
tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/182)

Fix reading from an offset in vmemcache_populate_value()

---

benchmarks/bench_micro.c
benchmarks/bench_simul.c
doc/vmemcache.md
src/libvmemcache.h
src/vmemcache.c
src/vmemcache.h
src/vmemcache_repl.c
src/vmemcache_repl.h
tests/vmemcache_test_basic.c
tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/167)

 vmemcache_evict: error out if repl_p_lru_evict fails

---

src/critnib.c
src/critnib.h
src/vmemcache.c
src/vmemcache_index.c
src/vmemcache_index.h
src/vmemcache_repl.c
src/vmemcache_repl.h

All within the same stat field — we might want to allow querying individual components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/161)

Track DRAM usage for index, heap and extents.

---

tests/test-mt.cmake
tests/vmemcache_test_mt.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/193)

test: fix run_test_get and run_test_get_put

---

benchmarks/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/201)

simul: fix enabling stats

---

src/vmemcache_heap.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/199)

heap: add vmcache_heap_add_mapping

---

src/out.c
src/ringbuf.c
src/util.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/202)

Ifdef out currently unused code.

---

CMakeLists.txt
libvmemcache.pc.in

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/203)

Install pkg-config file.

---

src/vmemcache.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/204)

add missing LOG calls to API functions

---

tests/vmemcache_test_basic.c

Will not pass without merging #182 first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/188)

test: add offset tests

---

tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/209)

test: add simple tests for vmemcache_errormsg()

---

tests/vmemcache_test_utilization.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/212)

test: set minimum space utilization to 87%

---

doc/vmemcache.md

Describe the new creation API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/211)

Man page updates.

---

src/vmemcache.c

We can implement this in the future, but for now, fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/210)

Disallow operating with two backings.

---

CMakeLists.txt
ChangeLog
README.md
src/libvmemcache.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/206)

common: 0.8 release

---

tests/helpers.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/215)

test: write a separate log file for each test

---

src/libvmemcache.h

We've released so it's perfect, right?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/216)

Withdraw a warning about API being unstable.

---

tests/test-utilization.cmake
tests/vmemcache_test_utilization.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/214)

test: add option to set seed for rand() and print it out

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/219)

add .gitignore to gh-pages branch

---

doc/vmemcache.md

Wasn't updated when the code got fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/220)

Fix an outdated problem marker in the doc.

---

doc/vmemcache.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/223)

doc: update man page to match the newest one from gh-pages branch

---

tests/CMakeLists.txt

The same check is done 7 lines above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/227)

test: remove duplicated check

---

utils/check_license/check-license.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/228)

common: fix printed name of file with incorrect license

---

doc/vmemcache.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/231)

doc: add signature of vmemcache_callback_on_<evict|miss>()

---

src/vmemcache.c
src/vmemcache_heap.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/232)

fix two regressions on 32-bit

---

tests/CMakeLists.txt
tests/test-twolevel.cmake
tests/twolevel.c

For review/merging; a prose version will follow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/235)

two-level cache: executable code

---

src/vmemcache_heap.c

Matches alignment of all media vmemcache is likely to be used on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/236)

bump guard size to 4096 bytes

---

doc/vmemcache.md
src/libvmemcache.h

Documentation improvements.
Fixed #240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/241)

Explain "entries" vs "heap entries".

---

doc/vmemcache.md
src/libvmemcache.h
src/libvmemcache.map
src/vmemcache.c
tests/vmemcache_test_basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/245)

add vmemcache_exists() to check entry existence without side-effects

---

utils/docker/images/Dockerfile.fedora-28
utils/docker/images/Dockerfile.ubuntu-18.04

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/246)

Update contact info.

---

src/util.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/250)

common: fix build on old gcc/clang

---

ChangeLog

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/vmemcache/252)

common: 0.8.1 release
